pipeline{
     agent any
     tools{
         maven 'maven'
         jdk 'jdk'

  }
  stages {
      stage("validate"){
          steps{
              sh 'mvn -f Challenge2 -B -DskipTests clean validate'
          }
      }
       stage("compile"){
          steps{
              sh 'mvn  -f Challenge2 compile'
          }
      }
       stage("Build & SonarQube analysis") {
           
            steps {
              withSonarQubeEnv('sonarserver') {
                sh 'java -version'
                sh 'mvn -f Challenge2 sonar:sonar'
              }
            }
          }
     stage("Quality gate") {
            steps {
                waitForQualityGate abortPipeline: true
            }
        }
       stage("test"){
          steps{
              sh 'mvn -f Challenge2 test '
          }
      }
       stage("package"){
          steps{
              sh 'mvn -f Challenge2 package '
          }
      }
     
     stage('Deploy to artifactory'){
        steps{
        rtUpload(
         serverId : 'artifactory-server',
         spec :'''{
           "files" :[
           {
           "pattern":"Challenge2/target/*.jar",
           "target":"art-doc-dev-loc"
           }
           ]
         }''',
         
      )
      }
     }
    }
    post {  
         always {  
             echo 'This will always run'  
         }  
         success {   
            echo "========Deploying executed successfully========"
             mail bcc: '', body: "<b>Example</b><br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER} <br> Success!! <br> URL de build: ${env.BUILD_URL}", cc: '', charset: 'UTF-8', from: 'sravaninuthanapati15@gmail.com', mimeType: 'text/html', replyTo: '', subject: "ERROR CI: Project name -> ${env.JOB_NAME}", to: "sravaninuthanapati15@gmail.com"; 
          
         }
         failure {  
             mail bcc: '', body: "<b>Example</b><br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER} <br> URL de build: ${env.BUILD_URL}", cc: '', charset: 'UTF-8', from: 'sravaninuthanapati15@gmail.com', mimeType: 'text/html', replyTo: '', subject: "ERROR CI: Project name -> ${env.JOB_NAME}", to: "sravaninuthanapati15@gmail.com";  
         }  
         unstable {  
             echo 'This will run only if the run was marked as unstable'  
         }  
         changed {  
             echo 'This will run only if the state of the Pipeline has changed'  
             echo 'For example, if the Pipeline was previously failing but is now successful'  
         }  
     }
  }
