pipeline{
     agent any
     tools{
         maven 'maven'
         jdk 'jdk'

  }
  stages {
      stage("validate"){
          steps{
              sh 'mvn -f Challenge2 -B -DskipTests clean validate'
          }
      }
       stage("compile"){
          steps{
              sh 'mvn  -f Challenge2 compile'
          }
      }
       stage("Build & SonarQube analysis") {
           
            steps {
              withSonarQubeEnv('sonarserver') {
                sh 'java -version'
                sh 'mvn -f Challenge2 sonar:sonar'
              }
            }
          }
     stage("Quality gate") {
            steps {
                waitForQualityGate abortPipeline: true
            }
        }
       
       stage("package"){
          steps{
               sh 'mvn -f Challenge2  -B -DskipTests package -Dbuild.number=-${BUILD_NUMBER} '
          }
      }
     
     stage('Deploy to artifactory'){
        steps{
        rtUpload(
         serverId : 'artifactory-server',
         spec :'''{
           "files" :[
           {
           "pattern":"Challenge2/target/*.jar",
           "target":"art-doc-dev-loc"
           }
           ]
         }''',
         
      )
      }
     }
    }
    post {  
         always {  
             echo 'This will always run'  
         }  
         success {   
            echo "========Deploying executed successfully========"
             mail bcc: '', body: "<b>Example</b><br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER} <br> Success!! <br> URL de build: ${env.BUILD_URL}", cc: '', charset: 'UTF-8', from: 'sravaninuthanapati15@gmail.com', mimeType: 'text/html', replyTo: '', subject: "ERROR CI: Project name -> ${env.JOB_NAME}", to: "sravaninuthanapati15@gmail.com"; 
           sshagent(['1076af24-fcf6-4ca0-a2f6-e79e16465615']){
                sh "ssh -o StrictHostKeyChecking=no ubuntu@35.154.165.223  'echo $HOME'"
                    sh 'scp -r /var/jenkins_home/workspace/springCricketpipeline/Challenge2/target/*.jar ubuntu@35.154.165.223:/home/ubuntu/artifacts'
           }
         withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: '5b4251f5-3bb4-46e4-a8ba-eba58d5a83d9', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
            s3Upload(pathStyleAccessEnabled: true, payloadSigningEnabled: true,file:'Challenge2-0.0.1-SNAPSHOT.jar', bucket:'artifactss3bucket', path:'var/jenkins_home/workspace/springCricketpipeline/Challenge2/target/*.jar')
       
         }
         }
         failure {  
             mail bcc: '', body: "<b>Example</b><br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER} <br> URL de build: ${env.BUILD_URL}", cc: '', charset: 'UTF-8', from: 'sravaninuthanapati15@gmail.com', mimeType: 'text/html', replyTo: '', subject: "ERROR CI: Project name -> ${env.JOB_NAME}", to: "sravaninuthanapati15@gmail.com";  
         }  
         unstable {  
             echo 'This will run only if the run was marked as unstable'  
         }  
         changed {  
             echo 'This will run only if the state of the Pipeline has changed'  
             echo 'For example, if the Pipeline was previously failing but is now successful'  
         }  
     }
  }
